<?php
$_SERVER['HTTP_HOST']='localhost';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/jwt.php';require_once __DIR__.'/../includes/rate_limiter.php';
function chLegacyToken(int$userId):string{$header=rtrim(strtr(base64_encode(json_encode(['typ'=>'JWT','alg'=>JWT_ALGORITHM])),'+/','-_'),'=');$payload=rtrim(strtr(base64_encode(json_encode(['user_id'=>$userId,'iat'=>time(),'exp'=>time()+3600])),'+/','-_'),'=');$signature=rtrim(strtr(base64_encode(hash_hmac('sha256',$header.'.'.$payload,JWT_SECRET,true)),'+/','-_'),'=');return$header.'.'.$payload.'.'.$signature;}
function chHttp(string$method,string$path,?array$body=null,?string$token=null):array{$base=rtrim(getenv('TEST_API_BASE')?:'http://localhost/sanie/backend/api','/');$headers="Content-Type: application/json\r\n".($token?"Authorization: Bearer {$token}\r\n":'');$options=['method'=>$method,'header'=>$headers,'ignore_errors'=>true,'timeout'=>10];if($body!==null)$options['content']=json_encode($body);$raw=file_get_contents("{$base}/{$path}",false,stream_context_create(['http'=>$options]));preg_match('/\s(\d{3})\s/',$http_response_header[0]??'',$m);return[(int)($m[1]??0),json_decode($raw?:'null',true),$raw?:''];}
function chAssert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
$db=(new Database())->getConnection();$emails=[];$failed=false;
try{foreach(['127.0.0.1','::1','unknown']as$ip)RateLimiter::clear('register:'.$ip);$email='ch-'.bin2hex(random_bytes(6)).'@example.invalid';$foreignEmail='ch-foreign-'.bin2hex(random_bytes(6)).'@example.invalid';$emails=[$email,$foreignEmail];$registration=['email'=>$email,'password'=>'oldPassword123','first_name'=>'Credential'];
    [$status,$registered]=chHttp('POST','auth/register',$registration);chAssert($status===201,'fresh registration failed');$sessionA=$registered['data']['token'];[$legacyStatus]=chHttp('GET','auth/me',null,chLegacyToken((int)$registered['data']['user']['id']));chAssert($legacyStatus===401,'unversioned legacy JWT was accepted');[$status,$login]=chHttp('POST','auth/login',['email'=>$email,'password'=>'oldPassword123']);chAssert($status===200,'initial login failed');$sessionB=$login['data']['token'];chAssert($sessionA!==$sessionB,'two sessions received identical JWTs');
    [$status]=chHttp('POST','auth/change-password',['current_password'=>'wrongPassword0','new_password'=>'newPassword456'],$sessionA);chAssert($status===401,'wrong current password was not rejected');foreach([$sessionA,$sessionB]as$token){[$me]=chHttp('GET','auth/me',null,$token);chAssert($me===200,'failed change revoked an existing session');}
    [$status]=chHttp('POST','auth/change-password',['new_password'=>'newPassword456'],$sessionA);chAssert($status===422,'missing current password was accepted');[$status]=chHttp('POST','auth/change-password',['current_password'=>'oldPassword123','new_password'=>'short'],$sessionA);chAssert($status===422,'weak new password was accepted');[$status]=chHttp('POST','auth/change-password',['current_password'=>'oldPassword123','new_password'=>'newPassword456','new_password_confirmation'=>'notMatching789'],$sessionA);chAssert($status===422,'confirmation mismatch was accepted');
    $s=$db->prepare("INSERT INTO users(email,password,first_name)VALUES(?,?,'Foreign')");$s->execute([$foreignEmail,password_hash('foreignPass123',PASSWORD_DEFAULT)]);$foreignId=(int)$db->lastInsertId();
    [$status,$changed,$raw]=chHttp('POST','auth/change-password',['current_password'=>'oldPassword123','new_password'=>'newPassword456','new_password_confirmation'=>'newPassword456','user_id'=>$foreignId,'email'=>$foreignEmail],$sessionA);chAssert($status===200&&isset($changed['data']['token']),'valid change did not return rotated session');$rotated=$changed['data']['token'];chAssert(!str_contains($raw,'oldPassword123')&&!str_contains($raw,'newPassword456')&&!str_contains($raw,'$2y$'),'credential response exposed sensitive data');
    foreach([$sessionA,$sessionB]as$token){[$me]=chHttp('GET','auth/me',null,$token);chAssert($me===401,'old session remained valid after password change');}[$me,$meBody]=chHttp('GET','auth/me',null,$rotated);chAssert($me===200&&(int)$meBody['data']['id']===(int)$registered['data']['user']['id'],'rotated current session cannot access /auth/me');
    [$oldLogin]=chHttp('POST','auth/login',['email'=>$email,'password'=>'oldPassword123']);chAssert($oldLogin===401,'old password still logs in');[$newLogin,$newBody]=chHttp('POST','auth/login',['email'=>$email,'password'=>'newPassword456']);chAssert($newLogin===200&&isset($newBody['data']['token']),'new password login failed');[$foreignLogin]=chHttp('POST','auth/login',['email'=>$foreignEmail,'password'=>'foreignPass123']);chAssert($foreignLogin===200,'cross-user payload changed foreign password');
    [$loggedOut]=chHttp('GET','auth/me');chAssert($loggedOut===401,'cleared-token logout state was not rejected');
    echo"PASS: password-change HTTP lifecycle verifies credentials, rotates current JWT, revokes other sessions, preserves failures, and prevents cross-user mutation\n";
}catch(Throwable$e){$failed=true;fwrite(STDERR,"FAIL: {$e->getMessage()}\n");}finally{foreach(['127.0.0.1','::1','unknown']as$ip)RateLimiter::clear('register:'.$ip);foreach($emails as$email){try{$s=$db->prepare('SELECT id FROM users WHERE email=?');$s->execute([$email]);$id=$s->fetchColumn();if($id)$db->prepare('DELETE FROM users WHERE id=?')->execute([$id]);}catch(Throwable$ignored){}}}exit($failed?1:0);
