<?php

$_SERVER['HTTP_HOST']='localhost';
require_once __DIR__.'/../database/SchemaMigrator.php';
require_once __DIR__.'/../services/FreshStartService.php';
require_once __DIR__.'/../includes/rate_limiter.php';

function fsAssert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function fsAdmin():PDO{$host=getenv('DB_HOST')?:'127.0.0.1';$user=getenv('DB_USERNAME')?:'root';$password=getenv('DB_PASSWORD')?:'';return new PDO("mysql:host={$host};charset=utf8mb4",$user,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}
function fsDb(string$name):PDO{$host=getenv('DB_HOST')?:'127.0.0.1';$user=getenv('DB_USERNAME')?:'root';$password=getenv('DB_PASSWORD')?:'';return new PDO("mysql:host={$host};dbname={$name};charset=utf8mb4",$user,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
function fsImportBaseline(PDO$db):void{$dump=file_get_contents(__DIR__.'/../database/fixtures/august-2026-baseline-schema.sql');preg_match_all('/^CREATE TABLE `[^`]+` \(.*?^\) ENGINE=.*?;/ms',$dump,$m);fsAssert(count($m[0])===17,'baseline table extraction failed');$db->exec('SET FOREIGN_KEY_CHECKS=0');foreach($m[0]as$sql)$db->exec($sql);$db->exec('SET FOREIGN_KEY_CHECKS=1');}
function fsServer(string$dbName):array{$port=random_int(20000,29000);$address="127.0.0.1:{$port}";$api=realpath(__DIR__.'/../api');$out=sys_get_temp_dir().DIRECTORY_SEPARATOR.'sanie-fresh-start-'.bin2hex(random_bytes(5));$env=getenv();$env['DB_DATABASE']=$dbName;$env['DB_HOST']=getenv('DB_HOST')?:'127.0.0.1';$env['DB_USERNAME']=getenv('DB_USERNAME')?:'root';$env['DB_PASSWORD']=getenv('DB_PASSWORD')?:'';$env['JWT_SECRET']='fresh-start-test-secret-at-least-32-characters';$env['APP_ENV']='testing';$env['APP_DEBUG']='0';$pipes=[];$process=proc_open([PHP_BINARY,'-S',$address,'-t',$api,$api.DIRECTORY_SEPARATOR.'index.php'],[0=>['pipe','r'],1=>['file',$out.'.out','a'],2=>['file',$out.'.err','a']],$pipes,dirname(__DIR__,2),$env);fsAssert(is_resource($process),'test server failed to start');fclose($pipes[0]);for($i=0;$i<50;$i++){usleep(100000);$socket=@fsockopen('127.0.0.1',$port,$n,$s,.2);if($socket){fclose($socket);return[$process,"http://{$address}",$out];}}throw new RuntimeException('test server was not ready');}
function fsStop(?array$server):void{if(!$server)return;[$p,,$out]=$server;if(is_resource($p)){proc_terminate($p);proc_close($p);}@unlink($out.'.out');@unlink($out.'.err');}
function fsHttp(string$base,string$method,string$path,?array$body=null,?string$token=null,array$extra=[]):array{$headers=['Content-Type: application/json'];if($token)$headers[]='Authorization: Bearer '.$token;foreach($extra as$k=>$v)$headers[]=$k.': '.$v;$options=['method'=>$method,'header'=>implode("\r\n",$headers)."\r\n",'ignore_errors'=>true,'timeout'=>65];if($body!==null)$options['content']=json_encode($body);$raw=file_get_contents($base.'/'.$path,false,stream_context_create(['http'=>$options]));preg_match('/\s(\d{3})\s/',$http_response_header[0]??'',$m);return[(int)($m[1]??0),json_decode($raw?:'null',true),$raw];}
function fsRegister(string$base,string$email):array{[$status,$body]=fsHttp($base,'POST','auth/register',['email'=>$email,'password'=>'freshStartPass123','first_name'=>'Synthetic']);fsAssert($status===201,"registration failed: {$status}");return[$body['data']['user'],$body['data']['token']];}
function fsClearLimits(int$userId):void{foreach(['prepare','verify','export','execute','status']as$action)foreach(['127.0.0.1','::1','unknown']as$ip)RateLimiter::clear("fresh-start:{$action}:{$userId}:{$ip}");}
function fsSeed(PDO$db,int$u):void{
    $account=(int)$db->query("SELECT id FROM accounts WHERE user_id={$u} ORDER BY id LIMIT 1")->fetchColumn();$category=(int)$db->query("SELECT id FROM categories WHERE user_id={$u} AND type='expense' ORDER BY id LIMIT 1")->fetchColumn();
    $db->prepare("INSERT INTO goals(user_id,name,target_amount,initial_amount,current_amount)VALUES(?,'Goal',1000,10,10)")->execute([$u]);$goal=(int)$db->lastInsertId();
    $db->prepare("INSERT INTO budgets(user_id,category_id,name,amount)VALUES(?,?,'Budget',500)")->execute([$u,$category]);
    $db->prepare("INSERT INTO recurring_transactions(user_id,account_id,category_id,amount,type,frequency,start_date)VALUES(?,?,?,25,'expense','monthly','2026-01-01')")->execute([$u,$account,$category]);$recurring=(int)$db->lastInsertId();
    $db->prepare("INSERT INTO people(user_id,name)VALUES(?,'Person')")->execute([$u]);$person=(int)$db->lastInsertId();
    $db->prepare("INSERT INTO karobar_transactions(user_id,person_id,type,amount,transaction_date)VALUES(?,?,'lent',50,'2026-01-02')")->execute([$u,$person]);
    $db->prepare("INSERT INTO transactions(user_id,account_id,from_account_id,category_id,amount,type,date,goal_id,recurring_definition_id,recurring_occurrence_date)VALUES(?,?,?,?,25,'goal_contribution','2026-01-03',?,?, '2026-01-03')")->execute([$u,$account,$account,$category,$goal,$recurring]);
    $db->prepare("INSERT INTO tasks(user_id,title,status,deleted_at)VALUES(?,'Soft deleted','pending',CURRENT_TIMESTAMP)")->execute([$u]);
    $db->prepare("INSERT INTO notifications(user_id,type,title)VALUES(?,'test','Notice')")->execute([$u]);
    $db->prepare("INSERT INTO notification_events(user_id,event_key,event_type)VALUES(?,'test:key','test')")->execute([$u]);
    $db->prepare("INSERT INTO reports(user_id,type,start_date,end_date,data)VALUES(?,'monthly','2026-01-01','2026-01-31','{}')")->execute([$u]);
    $db->prepare("INSERT INTO ai_analysis_history(user_id,analysis_type,start_date,end_date,insights)VALUES(?,'monthly','2026-01-01','2026-01-31','{}')")->execute([$u]);
    $db->prepare("INSERT INTO activity_logs(user_id,action)VALUES(?,'test')")->execute([$u]);
}

$name='sanie_fresh_start_test_'.bin2hex(random_bytes(5));$admin=fsAdmin();$server=null;$failed=false;
try{
    fsAssert((bool)preg_match('/^sanie_fresh_start_test_[a-f0-9]{10}$/',$name),'unsafe test database name');
    foreach(['127.0.0.1','::1','unknown']as$ip)RateLimiter::clear('register:'.$ip);
    $admin->exec("CREATE DATABASE `{$name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$db=fsDb($name);fsImportBaseline($db);(new SchemaMigrator($db))->run();$server=fsServer($name);[, $base]=$server;
    [$owner,$ownerToken]=fsRegister($base,'owner-'.bin2hex(random_bytes(4)).'@example.invalid');[$foreign,$foreignToken]=fsRegister($base,'foreign-'.bin2hex(random_bytes(4)).'@example.invalid');$ownerId=(int)$owner['id'];$foreignId=(int)$foreign['id'];fsClearLimits($ownerId);fsSeed($db,$ownerId);fsSeed($db,$foreignId);

    [$status,$prepared]=fsHttp($base,'POST','auth/fresh-start/prepare',[],$ownerToken);fsAssert($status===200,'prepare failed');$reset=$prepared['data'];fsAssert($reset['summary']['transactions']===1&&$reset['summary']['tasks']===1,'dynamic summary counts are wrong');
    [$status]=fsHttp($base,'POST','auth/fresh-start/verify',['operation_id'=>$reset['operation_id'],'password'=>'freshStartPass123','confirmation_phrase'=>'RESET ALL DATA'],$ownerToken);fsAssert($status===403,'missing reset intent was accepted');
    [$status]=fsHttp($base,'POST','auth/fresh-start/verify',['operation_id'=>$reset['operation_id'],'password'=>'wrongPassword123','confirmation_phrase'=>'RESET ALL DATA'],$ownerToken,['X-SanIE-Reset-Intent'=>$reset['intent_token']]);fsAssert($status===401,'wrong password was accepted');
    [$status,$verified]=fsHttp($base,'POST','auth/fresh-start/verify',['operation_id'=>$reset['operation_id'],'password'=>'freshStartPass123','confirmation_phrase'=>'RESET ALL DATA'],$ownerToken,['X-SanIE-Reset-Intent'=>$reset['intent_token']]);fsAssert($status===200,'valid verification failed');
    [$status]=fsHttp($base,'POST','auth/fresh-start/execute',['operation_id'=>$reset['operation_id'],'final_confirmation'=>true],$ownerToken,['X-SanIE-Reset-Intent'=>$reset['intent_token']]);fsAssert($status===403,'missing final confirmation token was accepted');
    [$status,$done]=fsHttp($base,'POST','auth/fresh-start/execute',['operation_id'=>$reset['operation_id'],'final_confirmation'=>true],$ownerToken,['X-SanIE-Reset-Intent'=>$reset['intent_token'],'X-SanIE-Reset-Confirmation'=>$verified['data']['confirmation_token']]);fsAssert($status===200,'reset execution failed');$newToken=$done['data']['token'];

    foreach(['transactions','attachments','recurring_transactions','budgets','goals','people','karobar_transactions','tasks','notifications','notification_events','reports','ai_analysis_history','activity_logs','subcategories']as$table){$count=(int)$db->query("SELECT COUNT(*) FROM `{$table}` WHERE user_id={$ownerId}")->fetchColumn();fsAssert($count===0,"{$table} was not cleared");}
    fsAssert((int)$db->query("SELECT COUNT(*) FROM accounts WHERE user_id={$ownerId}")->fetchColumn()===3,'default accounts were not restored');
    fsAssert((int)$db->query("SELECT COUNT(*) FROM categories WHERE user_id={$ownerId}")->fetchColumn()===12,'default categories were not restored');
    fsAssert((int)$db->query("SELECT COUNT(*) FROM transactions WHERE user_id={$foreignId}")->fetchColumn()===1,'foreign transactions changed');
    fsAssert((int)$db->query("SELECT COUNT(*) FROM tasks WHERE user_id={$foreignId}")->fetchColumn()===1,'foreign tasks changed');
    [$oldStatus]=fsHttp($base,'GET','auth/me',null,$ownerToken);fsAssert($oldStatus===401,'old session survived reset');[$newStatus]=fsHttp($base,'GET','auth/me',null,$newToken);fsAssert($newStatus===200,'replacement session is invalid');
    [$duplicateStatus]=fsHttp($base,'POST','auth/fresh-start/execute',['operation_id'=>$reset['operation_id'],'final_confirmation'=>true],$ownerToken,['X-SanIE-Reset-Intent'=>$reset['intent_token'],'X-SanIE-Reset-Confirmation'=>$verified['data']['confirmation_token']]);fsAssert($duplicateStatus===401,'duplicate reset request was accepted');fsAssert((int)$db->query("SELECT COUNT(*) FROM accounts WHERE user_id={$ownerId}")->fetchColumn()===3,'duplicate request changed restored defaults');
    [$dashStatus,$dashboard]=fsHttp($base,'GET','dashboard',null,$newToken);fsAssert($dashStatus===200&&abs((float)$dashboard['data']['total_balance'])<0.001,'dashboard did not return an empty balance');
    [$staleStatus]=fsHttp($base,'POST','transactions',['type'=>'expense','amount'=>5,'date'=>'2026-01-04','account_id'=>(int)$db->query("SELECT id FROM accounts WHERE user_id={$ownerId} LIMIT 1")->fetchColumn(),'category_id'=>(int)$db->query("SELECT id FROM categories WHERE user_id={$ownerId} AND type='expense' LIMIT 1")->fetchColumn()],$newToken,['X-SanIE-Data-Generation'=>'1']);fsAssert($staleStatus===409,'pre-reset offline generation was accepted');

    [$rollbackUser]=fsRegister($base,'rollback-'.bin2hex(random_bytes(4)).'@example.invalid');$rollbackId=(int)$rollbackUser['id'];fsSeed($db,$rollbackId);$service=new FreshStartService($db,function($point){if($point==='after_defaults')throw new RuntimeException('Injected rollback');});$preparedRollback=$service->prepare($rollbackId);$verifiedRollback=$service->verify($rollbackId,$preparedRollback['operation_id'],$preparedRollback['intent_token'],'freshStartPass123','RESET ALL DATA');try{$service->execute($rollbackId,$preparedRollback['operation_id'],$preparedRollback['intent_token'],$verifiedRollback['confirmation_token']);throw new RuntimeException('rollback injection was ignored');}catch(RuntimeException$e){fsAssert($e->getMessage()==='Injected rollback','unexpected rollback error');}fsAssert((int)$db->query("SELECT COUNT(*) FROM transactions WHERE user_id={$rollbackId}")->fetchColumn()===1,'failed reset did not roll back');
    [$cleanupUser]=fsRegister($base,'cleanup-'.bin2hex(random_bytes(4)).'@example.invalid');$cleanupId=(int)$cleanupUser['id'];fsSeed($db,$cleanupId);$cleanupTx=(int)$db->query("SELECT id FROM transactions WHERE user_id={$cleanupId} LIMIT 1")->fetchColumn();$db->prepare("INSERT INTO attachments(user_id,transaction_id,file_name,file_path)VALUES(?,?, 'receipt.pdf','../../outside.pdf')")->execute([$cleanupId,$cleanupTx]);$cleanupService=new FreshStartService($db);$cleanupPrepared=$cleanupService->prepare($cleanupId);$cleanupVerified=$cleanupService->verify($cleanupId,$cleanupPrepared['operation_id'],$cleanupPrepared['intent_token'],'freshStartPass123','RESET ALL DATA');$cleanupResult=$cleanupService->execute($cleanupId,$cleanupPrepared['operation_id'],$cleanupPrepared['intent_token'],$cleanupVerified['confirmation_token']);fsAssert($cleanupResult['cleanup_status']==='pending','unsafe file path was reported as cleaned');$cleanupStatus=$cleanupService->status($cleanupId,$cleanupPrepared['operation_id']);fsAssert($cleanupStatus['status']==='cleanup_pending'&&$cleanupStatus['cleanup']['pending']===1,'failed file cleanup was not retained for retry');
    $orphans=(int)$db->query("SELECT COUNT(*) FROM transactions t LEFT JOIN users u ON u.id=t.user_id WHERE u.id IS NULL")->fetchColumn();fsAssert($orphans===0,'foreign-key ownership records became orphaned');
    echo "PASS: Fresh Start authentication, CSRF intent, user isolation, dependencies, rollback, defaults, session rotation, stale-offline rejection, and empty dashboard verified\n";
}catch(Throwable$e){$failed=true;fwrite(STDERR,'FAIL: '.$e->getMessage()."\n");}
finally{fsStop($server);if(isset($db))$db=null;if(preg_match('/^sanie_fresh_start_test_[a-f0-9]{10}$/',$name))$admin->exec("DROP DATABASE IF EXISTS `{$name}`");}
exit($failed?1:0);
