<?php
$_SERVER['HTTP_HOST']='localhost';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/jwt.php';
function hhGet(string$path,int$user):array{$base=rtrim(getenv('TEST_API_BASE')?:'http://localhost/sanie/backend/api','/');$token=JWT::encode(['user_id'=>$user]);$raw=file_get_contents("{$base}/{$path}",false,stream_context_create(['http'=>['method'=>'GET','header'=>"Authorization: Bearer {$token}\r\n",'ignore_errors'=>true,'timeout'=>10]]));preg_match('/\s(\d{3})\s/',$http_response_header[0]??'',$m);return[(int)($m[1]??0),json_decode($raw?:'null',true)];}
$db=(new Database())->getConnection();$users=[];$failed=false;
try{
 foreach(['owner','foreign']as$label){$db->prepare("INSERT INTO users(email,password,first_name)VALUES(?,?,?)")->execute(['history-http-'.bin2hex(random_bytes(5)).'@example.invalid',password_hash('fixture',PASSWORD_DEFAULT),$label]);$users[$label]=(int)$db->lastInsertId();}$owner=$users['owner'];$foreign=$users['foreign'];$personIds=[];for($i=1;$i<=26;$i++){$db->prepare("INSERT INTO people(user_id,name,status)VALUES(?,?,'active')")->execute([$owner,sprintf('HTTP Person %02d',$i)]);$personIds[]=(int)$db->lastInsertId();}$db->prepare("INSERT INTO people(user_id,name,status)VALUES(?,'Foreign HTTP','active')")->execute([$foreign]);$foreignPerson=(int)$db->lastInsertId();
 $insert=$db->prepare("INSERT INTO karobar_transactions(user_id,person_id,type,amount,description,transaction_date)VALUES(?,?,'lent',?,?,?)");for($i=1;$i<=31;$i++)$insert->execute([$owner,$personIds[0],$i,"HTTP history {$i}",'2026-08-25']);$insert->execute([$foreign,$foreignPerson,999,'foreign','2026-08-25']);$db->prepare("UPDATE people SET status='archived' WHERE id=?")->execute([$personIds[0]]);
 [$status,$people]=hhGet('people?status=all&page=2&limit=10',$owner);if($status!==200||count($people['data']['people'])!==10||$people['data']['pagination']['total_rows']!==26||$people['data']['pagination']['page']!==2)throw new RuntimeException('People HTTP pagination metadata or page rows are incorrect');
 [, $ledger]=hhGet("people/{$personIds[0]}/ledger?page=2&limit=10",$owner);if(count($ledger['data']['ledger'])!==10||$ledger['data']['pagination']['total_rows']!==31||abs((float)$ledger['data']['ledger'][0]['running_balance']-66)>0.001)throw new RuntimeException('Person HTTP ledger pagination lost history or running continuity');
 [, $karobar]=hhGet("karobar?person_id={$personIds[0]}&page=2&limit=10",$owner);if(count($karobar['data']['transactions'])!==10||$karobar['data']['pagination']['total_rows']!==31||$karobar['data']['summary']['total_lent']!=496)throw new RuntimeException('Karobar HTTP page or full-filter totals are incorrect');
 [, $isolated]=hhGet("karobar?person_id={$foreignPerson}&page=1&limit=10",$owner);if($isolated['data']['transactions']||$isolated['data']['pagination']['total_rows']!==0)throw new RuntimeException('Karobar HTTP pagination leaked foreign history or counts');
 echo"PASS: People, archived person-ledger, and Karobar HTTP pagination are complete, continuous, and owner scoped\n";
}catch(Throwable$e){$failed=true;fwrite(STDERR,"FAIL: {$e->getMessage()}\n");}finally{foreach(array_reverse($users)as$user){try{$db->prepare('DELETE FROM users WHERE id=?')->execute([$user]);}catch(Throwable$ignored){}}}exit($failed?1:0);
