<?php
$_SERVER['HTTP_HOST']='localhost';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/jwt.php';
function mhRequest(string$method,string$path,int$user,?array$body=null):array{$base=rtrim(getenv('TEST_API_BASE')?:'http://localhost/sanie/backend/api','/');$token=JWT::encode(['user_id'=>$user]);$o=['method'=>$method,'header'=>"Content-Type: application/json\r\nAuthorization: Bearer {$token}\r\n",'ignore_errors'=>true,'timeout'=>10];if($body!==null)$o['content']=json_encode($body);$raw=file_get_contents("{$base}/{$path}",false,stream_context_create(['http'=>$o]));preg_match('/\s(\d{3})\s/',$http_response_header[0]??'',$m);return[(int)($m[1]??0),json_decode($raw?:'null',true)];}
$db=(new Database())->getConnection();$user=null;$failed=false;
try{
 $db->prepare("INSERT INTO users(email,password,first_name)VALUES(?,?,'Money HTTP')")->execute(['money-http-'.bin2hex(random_bytes(5)).'@example.invalid',password_hash('fixture',PASSWORD_DEFAULT)]);$user=(int)$db->lastInsertId();$db->prepare("INSERT INTO accounts(user_id,name,type,balance,opening_balance,is_active,is_default)VALUES(?,'HTTP Cash','cash',100,100,1,0)")->execute([$user]);$account=(int)$db->lastInsertId();$db->prepare("INSERT INTO categories(user_id,name,type,status,is_default)VALUES(?,'HTTP Expense','expense','active',0)")->execute([$user]);$category=(int)$db->lastInsertId();$payload=['type'=>'expense','amount'=>'1.999','date'=>'2026-08-25','account_id'=>$account,'category_id'=>$category,'description'=>'invalid precision','client_request_id'=>'req_money_http_precision_001'];
 [$status,$body]=mhRequest('POST','transactions',$user,$payload);if($status!==422||stripos((string)($body['message']??''),'decimal')===false)throw new RuntimeException('ordinary create did not return a controlled precision validation response');if((int)$db->query("SELECT COUNT(*) FROM transactions WHERE user_id={$user}")->fetchColumn()!==0)throw new RuntimeException('invalid HTTP create persisted a transaction');
 $payload['amount']='1.50';[$status,$created]=mhRequest('POST','transactions',$user,$payload);if($status!==201)throw new RuntimeException('valid HTTP create failed');$id=(int)$created['data']['id'];$version=(int)$created['data']['version'];$balance=(float)$db->query("SELECT balance FROM accounts WHERE id={$account}")->fetchColumn();
 [$status]=mhRequest('PUT',"transactions/{$id}",$user,['amount'=>'2.345','base_version'=>$version]);if($status!==422)throw new RuntimeException('ordinary edit did not reject excessive precision');if((float)$db->query("SELECT amount FROM transactions WHERE id={$id}")->fetchColumn()!==1.5||(float)$db->query("SELECT balance FROM accounts WHERE id={$account}")->fetchColumn()!==$balance)throw new RuntimeException('invalid HTTP edit produced a financial side effect');
 echo"PASS: ordinary transaction HTTP create/edit reject excessive precision without financial effects\n";
}catch(Throwable$e){$failed=true;fwrite(STDERR,"FAIL: {$e->getMessage()}\n");}finally{if($user){foreach(['notification_events','notifications','transactions','categories','accounts']as$table){try{$db->prepare("DELETE FROM {$table} WHERE user_id=?")->execute([$user]);}catch(Throwable$ignored){}}$db->prepare('DELETE FROM users WHERE id=?')->execute([$user]);}}exit($failed?1:0);
