<?php
$_SERVER['HTTP_HOST']='localhost';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../services/AccountingService.php';require_once __DIR__.'/../models/Budget.php';
function mpAssert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);echo"PASS: {$message}\n";}
$db=(new Database())->getConnection();$user=null;
try{
 $db->prepare("INSERT INTO users(email,password,first_name)VALUES(?,?,'Money Precision')")->execute(['money-precision-'.bin2hex(random_bytes(5)).'@example.invalid',password_hash('fixture',PASSWORD_DEFAULT)]);$user=(int)$db->lastInsertId();
 $db->prepare("INSERT INTO accounts(user_id,name,type,balance,opening_balance,is_active,is_default)VALUES(?,'Precision Cash','cash',0,0,1,0)")->execute([$user]);$account=(int)$db->lastInsertId();
 $db->prepare("INSERT INTO categories(user_id,name,type,status,is_default)VALUES(?,'Precision Income','income','active',0)")->execute([$user]);$incomeCat=(int)$db->lastInsertId();$db->prepare("INSERT INTO categories(user_id,name,type,status,is_default)VALUES(?,'Precision Expense','expense','active',0)")->execute([$user]);$expenseCat=(int)$db->lastInsertId();
 $budget=(int)(new Budget())->create(['user_id'=>$user,'name'=>'Precision Budget','amount'=>100,'period'=>'monthly','category_id'=>$expenseCat,'subcategory_id'=>null,'start_date'=>'2026-08-01','end_date'=>'2026-08-31','alert_threshold'=>80,'is_active'=>1]);$service=new AccountingService();
 $base=['type'=>'income','account_id'=>$account,'category_id'=>$incomeCat,'date'=>'2026-08-25','description'=>'precision'];$valid=['1','1.5','1.50','0.01','999999999999.99'];$ids=[];foreach($valid as$i=>$amount)$ids[]=$service->createTransaction($user,array_merge($base,['amount'=>$amount,'client_request_id'=>'money-valid-'.$i]));mpAssert(count($ids)===5,'ordinary create accepts whole, one-decimal, two-decimal, cent, and maximum supported values');
 $beforeCount=(int)$db->query("SELECT COUNT(*) FROM transactions WHERE user_id={$user}")->fetchColumn();$beforeBalance=(float)$db->query("SELECT balance FROM accounts WHERE id={$account}")->fetchColumn();$beforeBudget=(float)(new Budget())->getBudgetProgress($budget,$user)['spent'];$beforeNotifications=(int)$db->query("SELECT COUNT(*) FROM notifications WHERE user_id={$user}")->fetchColumn();
 foreach([0,-1,'1.999','0.001','abc','NaN','Infinity','1e999','1000000000000.00','1e2']as$amount){$rejected=false;try{$service->createTransaction($user,array_merge($base,['amount'=>$amount,'client_request_id'=>'money-invalid-'.md5((string)$amount)]));}catch(InvalidArgumentException$e){$rejected=true;}mpAssert($rejected,"ordinary create rejects invalid amount ".var_export($amount,true));}
 mpAssert((int)$db->query("SELECT COUNT(*) FROM transactions WHERE user_id={$user}")->fetchColumn()===$beforeCount&&(float)$db->query("SELECT balance FROM accounts WHERE id={$account}")->fetchColumn()===$beforeBalance&&(float)(new Budget())->getBudgetProgress($budget,$user)['spent']===$beforeBudget&&(int)$db->query("SELECT COUNT(*) FROM notifications WHERE user_id={$user}")->fetchColumn()===$beforeNotifications,'rejected creates have no transaction, balance, budget, or notification effects');
 $editId=(int)$ids[0];$version=(int)$db->query("SELECT version FROM transactions WHERE id={$editId}")->fetchColumn();foreach(['2.345','abc','1e2']as$amount){$rejected=false;try{$service->updateTransaction($editId,$user,['amount'=>$amount],$version);}catch(InvalidArgumentException$e){$rejected=true;}mpAssert($rejected,"ordinary edit rejects invalid amount {$amount}");}
 $service->updateTransaction($editId,$user,['amount'=>'2.50'],$version);mpAssert((float)$db->query("SELECT amount FROM transactions WHERE id={$editId}")->fetchColumn()===2.5,'ordinary edit accepts a valid two-decimal amount');
 $retryPayload=array_merge($base,['amount'=>'3.25','client_request_id'=>'money-retry-safe']);$first=$service->createTransaction($user,$retryPayload);mpAssert($first>0&&(int)$db->query("SELECT COUNT(*) FROM transactions WHERE user_id={$user} AND client_request_id='money-retry-safe'")->fetchColumn()===1,'strict validation preserves the transaction identity used by API idempotency');
 $invalidKey='money-invalid-retry';try{$service->createTransaction($user,array_merge($base,['amount'=>'4.444','client_request_id'=>$invalidKey]));}catch(Throwable$e){}$created=$service->createTransaction($user,array_merge($base,['amount'=>'4.44','client_request_id'=>$invalidKey]));mpAssert($created>0,'invalid attempt leaves no partial idempotency record and a corrected retry can succeed');
}finally{if($user){foreach(['notification_events','notifications','transactions','budgets','categories','accounts']as$table)$db->prepare("DELETE FROM {$table} WHERE user_id=?")->execute([$user]);$db->prepare('DELETE FROM users WHERE id=?')->execute([$user]);}}
