<?php

$_SERVER['HTTP_HOST']='localhost';
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/../models/Person.php';
require_once __DIR__.'/../services/KarobarService.php';
require_once __DIR__.'/../services/KarobarOutstandingService.php';
require_once __DIR__.'/../database/SchemaMigrator.php';

function pdAssert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
function pdClose(float$expected,float$actual,string$message):void{if(abs($expected-$actual)>.001)throw new RuntimeException("$message: expected $expected, got $actual");}

$db=(new Database())->getConnection();if(!$db)exit(1);
$users=[];$passed=0;$failed=0;
$run=function(string$name,callable$test)use(&$passed,&$failed):void{try{$test();$passed++;echo"PASS: $name\n";}catch(Throwable$e){$failed++;fwrite(STDERR,"FAIL: $name - {$e->getMessage()}\n");}};
try{
    foreach(['owner','foreign']as$label){$s=$db->prepare("INSERT INTO users(email,password,first_name)VALUES(?,?,'Person Delete')");$s->execute(['pd-'.$label.'-'.bin2hex(random_bytes(5)).'@example.invalid',password_hash('fixture',PASSWORD_DEFAULT)]);$users[$label]=(int)$db->lastInsertId();}
    $owner=$users['owner'];$foreign=$users['foreign'];$model=new Person();$out=new KarobarOutstandingService();$service=new KarobarService();$past=date('Y-m-d',strtotime('-10 days'));$today=date('Y-m-d');
    $person=function(int$user,string$name)use($db):int{$s=$db->prepare("INSERT INTO people(user_id,name,type,status)VALUES(?,?,'person','active')");$s->execute([$user,$name]);return(int)$db->lastInsertId();};
    $tx=function(int$user,int$person,string$type,float$amount,string$date,?string$due=null)use($db):int{$s=$db->prepare("INSERT INTO karobar_transactions(user_id,person_id,type,amount,transaction_date,due_date,description)VALUES(?,?,?,?,?,?,?)");$s->execute([$user,$person,$type,$amount,$date,$due,'Phase 8 fixture']);return(int)$db->lastInsertId();};

    $run('person without financial history is permanently deleted',function()use($person,$owner,$model):void{$p=$person($owner,'No history');$r=$model->removeSafely($p,$owner);pdAssert($r['action']==='deleted','empty person was not hard deleted');pdAssert($model->findById($p,$owner)===false,'deleted person still exists');});

    $run('active payable archives with outstanding and overdue unchanged',function()use($db,$person,$tx,$owner,$past,$model,$out):void{$p=$person($owner,'Active payable');$tx($owner,$p,'borrowed',10000,$past,$past);$before=$out->getPersonPosition($owner,$p);$r=$model->removeSafely($p,$owner);$after=$out->getPersonPosition($owner,$p);pdAssert($r['action']==='archived','history person was not archived');pdClose(10000,$after['payable_outstanding'],'payable changed');pdClose($before['overdue_payable'],$after['overdue_payable'],'overdue changed');pdAssert($model->findById($p,$owner)['status']==='archived','archived identity is not resolvable');pdAssert(count(array_filter($model->findAll($owner,['status'=>'active']),fn($x)=>(int)$x['id']===$p))===0,'archived person remained active');pdAssert(count(array_filter($model->findAll($owner,['status'=>'archived']),fn($x)=>(int)$x['id']===$p))===1,'archived list cannot resolve person');try{$db->prepare('DELETE FROM people WHERE id=?')->execute([$p]);throw new RuntimeException('direct delete unexpectedly succeeded');}catch(PDOException$e){pdAssert((string)$e->getCode()==='23000','direct delete failed for the wrong reason');}});

    $run('partial repayment rows and allocation survive archive',function()use($person,$tx,$owner,$past,$today,$model,$out):void{$p=$person($owner,'Partial payable');$tx($owner,$p,'borrowed',12000,$past,$past);$tx($owner,$p,'repaid',5000,$today);$before=$out->getPersonPosition($owner,$p);$model->removeSafely($p,$owner);$after=$out->getPersonPosition($owner,$p);pdClose(7000,$after['payable_outstanding'],'partial payable changed');pdClose($before['overdue_payable'],$after['overdue_payable'],'partial overdue changed');pdAssert($after['transaction_count']==2,'partial history disappeared');});

    $run('fully settled and receivable histories are preserved',function()use($person,$tx,$owner,$past,$today,$model,$out):void{$settled=$person($owner,'Settled history');$tx($owner,$settled,'borrowed',10000,$past,$past);$tx($owner,$settled,'repaid',10000,$today);$model->removeSafely($settled,$owner);pdAssert($out->getPersonPosition($owner,$settled)['settled_count']===1,'settled origin disappeared');$receivable=$person($owner,'Receivable history');$tx($owner,$receivable,'lent',10000,$past,$past);$tx($owner,$receivable,'returned',4000,$today);$model->removeSafely($receivable,$owner);$position=$out->getPersonPosition($owner,$receivable);pdClose(6000,$position['receivable_outstanding'],'receivable changed');pdClose(6000,$position['overdue_receivable'],'receivable overdue changed');});

    $run('credit purchase pair and expense survive archive',function()use($db,$person,$owner,$past,$today,$model,$service,$out):void{$p=$person($owner,'Credit vendor');$s=$db->prepare("INSERT INTO categories(user_id,name,type,status,is_default)VALUES(?,'PD Credit','expense','active',0)");$s->execute([$owner]);$category=(int)$db->lastInsertId();$s=$db->prepare("INSERT INTO accounts(user_id,name,type,balance,opening_balance,is_active,is_default)VALUES(?,'PD Cash','cash',20000,20000,1,0)");$s->execute([$owner]);$account=(int)$db->lastInsertId();$purchase=$service->processCreditPurchase(['amount'=>5000,'creditor_id'=>$p,'category_id'=>$category,'date'=>$past,'description'=>'Archived credit','due_date'=>$past,'client_request_id'=>'pd-credit-'.bin2hex(random_bytes(5))],$owner);$service->processRepayment(['person_id'=>$p,'account_id'=>$account,'amount'=>2000,'transaction_date'=>$today,'client_request_id'=>'pd-repay-'.bin2hex(random_bytes(5))],$owner);$model->removeSafely($p,$owner);pdClose(3000,$out->getPersonPosition($owner,$p)['payable_outstanding'],'credit payable changed');$resource=$service->getCreditPurchaseResource($purchase['karobar_id'],$owner);pdAssert((int)$resource['transaction']['karobar_transaction_id']===$purchase['karobar_id'],'expense forward link broke');pdAssert((int)$resource['payable']['expense_transaction_id']===$purchase['transaction_id'],'payable reverse link broke');pdClose(5000,(float)$resource['transaction']['amount'],'expense amount changed');try{$service->processRepayment(['person_id'=>$p,'account_id'=>$account,'amount'=>1,'transaction_date'=>$today,'client_request_id'=>'pd-block-'.bin2hex(random_bytes(5))],$owner);throw new RuntimeException('archived person accepted new payment');}catch(KarobarValidationException$e){pdAssert(stripos($e->getMessage(),'archived')!==false,'archived rejection was unclear');}});

    $run('restore makes person active without changing finance',function()use($person,$tx,$owner,$past,$model,$out):void{$p=$person($owner,'Restore person');$tx($owner,$p,'borrowed',12000,$past,$past);$model->removeSafely($p,$owner);$before=$out->getPersonPosition($owner,$p);$record=$model->findById($p,$owner);$record['status']='active';pdAssert($model->update($p,$owner,$record),'restore update failed');$after=$out->getPersonPosition($owner,$p);pdAssert($model->findById($p,$owner)['status']==='active','restore did not activate person');pdClose($before['payable_outstanding'],$after['payable_outstanding'],'restore changed outstanding');pdClose($before['overdue_payable'],$after['overdue_payable'],'restore changed overdue');});

    $run('foreign user cannot remove person',function()use($person,$foreign,$owner,$model):void{$p=$person($foreign,'Foreign person');pdAssert($model->removeSafely($p,$owner)===null,'foreign person was removed');pdAssert($model->findById($p,$foreign)!==false,'foreign person disappeared');});

    $run('schema migration remains current and repeat-safe',function()use($db):void{$first=(new SchemaMigrator($db))->run();$second=(new SchemaMigrator($db))->run();pdAssert(!$first['applied']&&!$second['applied'],'current migration was not a no-op');pdAssert($first['migration_id']===SchemaMigrator::CURRENT_MIGRATION_ID,'wrong current migration ID');});
}finally{foreach(array_reverse($users)as$id){try{$db->prepare('DELETE FROM users WHERE id=?')->execute([$id]);}catch(Throwable$e){fwrite(STDERR,"Cleanup warning: {$e->getMessage()}\n");}}}
echo"RESULT: $passed passed, $failed failed, 0 skipped\n";exit($failed?1:0);
