<?php

$_SERVER['HTTP_HOST']='localhost';
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/../services/ReportingPaginationService.php';
require_once __DIR__.'/../database/SchemaMigrator.php';

function rpAssert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
function rpClose(float$expected,float$actual,string$message):void{if(abs($expected-$actual)>.001)throw new RuntimeException("{$message}: expected {$expected}, got {$actual}");}
$db=(new Database())->getConnection();$users=[];$passed=0;$failed=0;
$run=function(string$name,callable$test)use(&$passed,&$failed):void{try{$test();$passed++;echo"PASS: {$name}\n";}catch(Throwable$e){$failed++;fwrite(STDERR,"FAIL: {$name} - {$e->getMessage()}\n");}};
try{
    foreach(['owner','foreign']as$label){$s=$db->prepare("INSERT INTO users(email,password,first_name)VALUES(?,?,'Phase Ten')");$s->execute(['rp-'.$label.'-'.bin2hex(random_bytes(5)).'@example.invalid',password_hash('fixture',PASSWORD_DEFAULT)]);$users[$label]=(int)$db->lastInsertId();}
    $owner=$users['owner'];$foreign=$users['foreign'];
    $account=function(int$user,string$name,float$opening)use($db):int{$s=$db->prepare("INSERT INTO accounts(user_id,name,type,balance,opening_balance,is_active,is_default)VALUES(?,?,'cash',?,?,1,0)");$s->execute([$user,$name,$opening,$opening]);return(int)$db->lastInsertId();};
    $category=function(int$user,string$name,string$type)use($db):int{$s=$db->prepare("INSERT INTO categories(user_id,name,type,status,is_default)VALUES(?,?,?,'active',0)");$s->execute([$user,$name,$type]);return(int)$db->lastInsertId();};
    $reportAccount=$account($owner,'RP Report',0);$ledgerAccount=$account($owner,'RP Ledger',10000);$foreignAccount=$account($foreign,'RP Foreign',900000);
    $expenseCategory=$category($owner,'RP Expense','expense');$incomeCategory=$category($owner,'RP Income','income');
    $insert=$db->prepare("INSERT INTO transactions(user_id,account_id,from_account_id,to_account_id,category_id,amount,type,date,description,created_at)VALUES(?,?,?,?,?,?,?,?,?,'2026-08-17 12:00:00')");
    $db->beginTransaction();
    for($i=0;$i<1250;$i++)$insert->execute([$owner,$reportAccount,$reportAccount,null,$expenseCategory,10,'expense','2026-10-'.str_pad((string)(1+$i%20),2,'0',STR_PAD_LEFT),'RP bulk expense']);
    for($i=0;$i<250;$i++)$insert->execute([$owner,$reportAccount,null,$reportAccount,$incomeCategory,20,'income','2026-10-'.str_pad((string)(1+$i%20),2,'0',STR_PAD_LEFT),'RP bulk income']);
    for($i=0;$i<50;$i++)$insert->execute([$owner,$ledgerAccount,$ledgerAccount,null,$expenseCategory,100,'expense',$i<10?'2026-09-01':'2026-09-02','RP ledger expense']);
    for($i=0;$i<50;$i++)$insert->execute([$owner,$ledgerAccount,null,$ledgerAccount,$incomeCategory,200,'income','2026-09-02','RP ledger income']);
    $insert->execute([$foreign,$foreignAccount,$foreignAccount,null,$expenseCategory,999999,'expense','2026-10-10','RP foreign expense']);
    $db->commit();
    $service=new ReportingPaginationService($db);$reportFilters=['start_date'=>'2026-10-01','end_date'=>'2026-10-31','account_id'=>$reportAccount];

    $run('report count and summary use all 1500 matching rows',function()use($service,$owner,$reportFilters):void{$r=$service->incomeExpensePage($owner,$reportFilters,1,50);rpAssert($r['pagination']['total_rows']===1500,'full row count is wrong');rpAssert($r['pagination']['total_pages']===30,'page count is wrong');rpClose(12500,$r['summary']['total_expense'],'full expense');rpClose(5000,$r['summary']['total_income'],'full income');rpClose(-7500,$r['summary']['net'],'full net');rpAssert(count($r['rows'])===50,'page was not bounded');});
    $run('all report pages cover every matching ID exactly once',function()use($service,$db,$owner,$reportFilters,$reportAccount):void{$actual=[];for($page=1;$page<=11;$page++){foreach($service->incomeExpensePage($owner,$reportFilters,$page,137)['rows']as$row)$actual[]=(int)$row['id'];}$s=$db->prepare("SELECT id FROM transactions WHERE user_id=? AND account_id=? AND date BETWEEN '2026-10-01' AND '2026-10-31' ORDER BY date,created_at,id");$s->execute([$owner,$reportAccount]);$expected=array_map('intval',$s->fetchAll(PDO::FETCH_COLUMN));rpAssert($actual===$expected,'page union has omissions, duplicates, or ordering drift');rpAssert(count(array_unique($actual))===1500,'duplicate page IDs found');});
    $run('middle, partial last, beyond-last and empty pages preserve full summary',function()use($service,$owner,$reportFilters):void{$middle=$service->incomeExpensePage($owner,$reportFilters,6,137);$last=$service->incomeExpensePage($owner,$reportFilters,11,137);$beyond=$service->incomeExpensePage($owner,$reportFilters,12,137);$empty=$service->incomeExpensePage($owner,['start_date'=>'2040-01-01','end_date'=>'2040-01-31'],1,50);rpAssert(count($middle['rows'])===137,'middle page size wrong');rpAssert(count($last['rows'])===130,'partial last page wrong');rpAssert($beyond['rows']===[]&&$beyond['pagination']['total_rows']===1500,'beyond-last convention wrong');rpClose(12500,$last['summary']['total_expense'],'last-page summary changed');rpAssert($empty['rows']===[]&&$empty['pagination']['total_rows']===0,'empty rows/count wrong');rpClose(0,$empty['summary']['total_income'],'empty income');rpClose(0,$empty['summary']['total_expense'],'empty expense');});
    $run('report filters scope rows count and totals identically',function()use($service,$owner,$reportFilters):void{$expense=$service->incomeExpensePage($owner,array_merge($reportFilters,['type'=>'expense','search'=>'bulk expense']),1,100);rpAssert($expense['pagination']['total_rows']===1250,'filtered count wrong');rpClose(12500,$expense['summary']['total_expense'],'filtered expense wrong');rpClose(0,$expense['summary']['total_income'],'filtered income wrong');foreach($expense['rows']as$row)rpAssert($row['type']==='expense'&&$row['description']==='RP bulk expense','row predicate differs from aggregate predicate');});
    $run('report canonical movement semantics exclude transfer goal and repayment from expense',function()use($db,$insert,$service,$owner,$reportAccount,$ledgerAccount,$expenseCategory):void{$insert->execute([$owner,null,$ledgerAccount,$reportAccount,null,5000,'transfer','2026-11-01','RP transfer']);$insert->execute([$owner,$reportAccount,$reportAccount,null,null,2000,'goal_contribution','2026-11-02','RP goal']);$insert->execute([$owner,null,null,null,$expenseCategory,5000,'expense','2026-11-03','RP credit purchase']);$insert->execute([$owner,$ledgerAccount,$ledgerAccount,null,$expenseCategory,20,'expense','2026-11-04','RP transfer fee']);$s=$db->prepare("INSERT INTO people(user_id,name,type,status)VALUES(?,'RP Person','person','active')");$s->execute([$owner]);$person=(int)$db->lastInsertId();$s=$db->prepare("INSERT INTO karobar_transactions(user_id,person_id,type,amount,account_id,transaction_date,description)VALUES(?,?,'repaid',1000,?,'2026-11-05','RP repayment')");$s->execute([$owner,$person,$reportAccount]);$r=$service->incomeExpensePage($owner,['start_date'=>'2026-11-01','end_date'=>'2026-11-30'],1,50);rpAssert($r['pagination']['total_rows']===4,'transaction report unexpectedly included Karobar repayment');rpClose(5020,$r['summary']['total_expense'],'canonical expense total');rpClose(0,$r['summary']['total_income'],'canonical income total');});
    $ledgerFilters=['account_id'=>$ledgerAccount,'start_date'=>'2026-09-01','end_date'=>'2026-09-02'];
    $run('five-page ledger has exact page opening and running continuity',function()use($service,$owner,$ledgerFilters):void{$expectedOpen=[1=>10000,2=>8000,3=>6000,4=>7000,5=>11000];$previousClosing=null;for($page=1;$page<=5;$page++){$r=$service->ledgerPage($owner,$ledgerFilters,$page,20);rpClose($expectedOpen[$page],$r['summary']['page_opening'],"page {$page} opening");$first=$r['transactions'][0];rpClose((float)$r['summary']['page_opening']+(float)$first['cash_delta'],(float)$first['running_balance'],"page {$page} first running");if($previousClosing!==null)rpClose($previousClosing,(float)$r['summary']['page_opening'],"page {$page} continuity");$pageRows=$r['transactions'];$last=end($pageRows);$previousClosing=(float)$last['running_balance'];}rpClose(15000,$previousClosing,'final ledger closing');});
    $run('date-filtered range opening includes all prior effects',function()use($service,$owner,$ledgerAccount):void{$r=$service->ledgerPage($owner,['account_id'=>$ledgerAccount,'start_date'=>'2026-09-02','end_date'=>'2026-09-02'],1,20);rpClose(9000,$r['summary']['range_opening'],'filtered range opening');rpClose(9000,$r['summary']['page_opening'],'filtered first page opening');rpAssert($r['pagination']['total_rows']===90,'filtered row count wrong');});
    $run('non-date filters hide rows without rewriting real running balance',function()use($service,$owner,$ledgerAccount):void{$r=$service->ledgerPage($owner,['account_id'=>$ledgerAccount,'start_date'=>'2026-09-01','end_date'=>'2026-09-02','search'=>'ledger income'],1,20);rpAssert($r['pagination']['total_rows']===50,'search count wrong');rpClose(5000,$r['summary']['page_opening'],'hidden expenses were omitted from real balance');rpClose(5200,$r['transactions'][0]['running_balance'],'filtered first running balance');});
    $run('ledger ordering and page boundaries are repeatable',function()use($service,$owner,$ledgerFilters):void{$a=$service->ledgerPage($owner,$ledgerFilters,3,20);$b=$service->ledgerPage($owner,$ledgerFilters,3,20);rpAssert(array_column($a['transactions'],'source_id')===array_column($b['transactions'],'source_id'),'stable ordering changed');rpClose($a['summary']['page_opening'],$b['summary']['page_opening'],'stable page opening');});
    $run('report and ledger exclude foreign-user rows',function()use($service,$owner,$reportFilters,$ledgerFilters):void{rpAssert($service->incomeExpensePage($owner,$reportFilters,1,200)['pagination']['total_rows']===1500,'foreign report row leaked');rpAssert($service->ledgerPage($owner,$ledgerFilters,1,100)['pagination']['total_rows']===100,'foreign ledger row leaked');});
    $run('schema migration remains current and repeat-safe',function()use($db):void{$a=(new SchemaMigrator($db))->run();$b=(new SchemaMigrator($db))->run();rpAssert(!$a['applied']&&!$b['applied'],'migration was not a no-op');rpAssert($a['migration_id']===SchemaMigrator::CURRENT_MIGRATION_ID,'wrong migration ID');});
}finally{if($db->inTransaction())$db->rollBack();foreach(array_reverse($users)as$id){try{foreach(['karobar_transactions','transactions','people','categories','accounts']as$table)$db->prepare("DELETE FROM {$table} WHERE user_id=?")->execute([$id]);$db->prepare('DELETE FROM users WHERE id=?')->execute([$id]);}catch(Throwable$e){fwrite(STDERR,"Cleanup warning: {$e->getMessage()}\n");}}}
echo"RESULT: {$passed} passed, {$failed} failed, 0 skipped\n";exit($failed?1:0);
