<?php

$_SERVER['HTTP_HOST']='localhost';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/jwt.php';
function rph(string$method,string$path,int$user):array{$base=rtrim(getenv('TEST_API_BASE')?:'http://localhost/sanie/backend/api','/');$token=JWT::encode(['user_id'=>$user]);$raw=file_get_contents("{$base}/{$path}",false,stream_context_create(['http'=>['method'=>$method,'header'=>"Authorization: Bearer {$token}\r\n",'ignore_errors'=>true,'timeout'=>10]]));$line=$http_response_header[0]??'';preg_match('/\s(\d{3})\s/',$line,$m);return[(int)($m[1]??0),json_decode($raw?:'null',true)];}
function rphAssert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
$db=(new Database())->getConnection();$users=[];$failed=false;
try{foreach(['owner','foreign']as$label){$s=$db->prepare("INSERT INTO users(email,password,first_name)VALUES(?,?,'RP HTTP')");$s->execute(['rph-'.$label.'-'.bin2hex(random_bytes(5)).'@example.invalid',password_hash('fixture',PASSWORD_DEFAULT)]);$users[$label]=(int)$db->lastInsertId();}$owner=$users['owner'];$foreign=$users['foreign'];
    $account=function(int$user,string$name)use($db):int{$s=$db->prepare("INSERT INTO accounts(user_id,name,type,balance,opening_balance,is_active,is_default)VALUES(?,?,'cash',1000,1000,1,0)");$s->execute([$user,$name]);return(int)$db->lastInsertId();};$ownedAccount=$account($owner,'RPH Owned');$foreignAccount=$account($foreign,'RPH Foreign');
    $s=$db->prepare("INSERT INTO categories(user_id,name,type,status,is_default)VALUES(?,'RPH Expense','expense','active',0)");$s->execute([$owner]);$category=(int)$db->lastInsertId();$insert=$db->prepare("INSERT INTO transactions(user_id,account_id,from_account_id,category_id,amount,type,date,description,created_at)VALUES(?,?,?,?,?,'expense','2026-12-01',?,'2026-08-17 13:00:00')");for($i=1;$i<=5;$i++)$insert->execute([$owner,$ownedAccount,$ownedAccount,$category,$i*10,"RPH row {$i}"]);
    [$status,$report]=rph('GET','reports/income-expense?start_date=2026-12-01&end_date=2026-12-31&page=2&limit=2',$owner);rphAssert($status===200&&$report['data']['pagination']['total_rows']===5&&count($report['data']['rows'])===2,'report HTTP pagination contract failed');rphAssert((float)$report['data']['summary']['total_expense']===150.0,'report HTTP summary used current page');
    [$status,$ledger]=rph('GET',"ledger?account_id={$ownedAccount}&start_date=2026-12-01&end_date=2026-12-31&page=2&limit=2",$owner);rphAssert($status===200&&$ledger['data']['pagination']['total_rows']===5,'ledger HTTP pagination contract failed');$first=$ledger['data']['transactions'][0];rphAssert(abs((float)$first['running_balance']-((float)$ledger['data']['summary']['page_opening']+(float)$first['cash_delta']))<.001,'ledger HTTP page opening continuity failed');
    [$status]=rph('GET',"ledger?account_id={$foreignAccount}",$owner);rphAssert($status===404,'foreign ledger account did not return tenant-isolated 404');[, $foreignReport]=rph('GET','reports/income-expense?start_date=2026-12-01&end_date=2026-12-31',$foreign);rphAssert($foreignReport['data']['pagination']['total_rows']===0,'foreign report included owner rows');
    echo"PASS: report and ledger HTTP pagination metadata, full summaries, page openings, and tenant isolation are coherent\n";
}catch(Throwable$e){$failed=true;fwrite(STDERR,"FAIL: {$e->getMessage()}\n");}finally{foreach(array_reverse($users)as$id){try{foreach(['transactions','categories','accounts']as$table)$db->prepare("DELETE FROM {$table} WHERE user_id=?")->execute([$id]);$db->prepare('DELETE FROM users WHERE id=?')->execute([$id]);}catch(Throwable$ignored){}}}exit($failed?1:0);
