create or replace function public.sanie_require_generation(p_generation bigint)
returns uuid language plpgsql security definer set search_path=pg_catalog,public as $$
declare u uuid:=auth.uid(); g bigint;
begin
 if u is null then raise exception using errcode='P0001',message='UNAUTHENTICATED'; end if;
 select data_generation into g from public.profiles where id=u for update;
 if not found then raise exception using errcode='P0001',message='UNAUTHENTICATED'; end if;
 if p_generation is distinct from g then raise exception using errcode='P0001',message='DATA_GENERATION_MISMATCH'; end if;
 return u;
end $$;

create or replace function public.sanie_rebuild_account(p_account uuid,p_user uuid)
returns numeric language plpgsql security definer set search_path=pg_catalog,public as $$
declare b numeric(15,2);
begin
 select a.opening_balance + coalesce(sum(case
  when t.transaction_type='income' and coalesce(t.to_account_id,t.account_id)=p_account then t.amount
  when t.transaction_type='expense' and coalesce(t.from_account_id,t.account_id)=p_account then -t.amount
  when t.transaction_type='transfer' and t.from_account_id=p_account then -t.amount
  when t.transaction_type='transfer' and t.to_account_id=p_account then t.amount
  when t.transaction_type='goal_contribution' and coalesce(t.from_account_id,t.account_id)=p_account then -t.amount
  else 0 end),0) into b
 from public.accounts a left join public.transactions t on t.user_id=p_user and t.deleted_at is null
 where a.id=p_account and a.user_id=p_user group by a.opening_balance;
 if b is null then raise exception using errcode='P0001',message='FORBIDDEN_REFERENCE'; end if;
 select b + coalesce(sum(case when k.transaction_type in ('lent','repaid') and k.account_id=p_account then -k.amount when k.transaction_type in ('borrowed','returned') and k.account_id=p_account then k.amount else 0 end),0) into b from public.karobar_transactions k where k.user_id=p_user and k.deleted_at is null;
 update public.accounts set balance=b where id=p_account and user_id=p_user;
 return b;
end $$;
create or replace function public.sanie_rebuild_goal(p_goal uuid,p_user uuid)
returns void language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 update public.goals g set current_amount=g.initial_amount+coalesce((select sum(t.amount) from public.transactions t where t.goal_id=g.id and t.user_id=p_user and t.transaction_type='goal_contribution' and t.deleted_at is null),0), status=case when g.status='active' and g.initial_amount+coalesce((select sum(t.amount) from public.transactions t where t.goal_id=g.id and t.user_id=p_user and t.transaction_type='goal_contribution' and t.deleted_at is null),0)>=g.target_amount then 'completed'::public.sanie_goal_status else g.status end where g.id=p_goal and g.user_id=p_user;
end $$;
create or replace function public.sanie_create_ordinary(p_id uuid,p_type public.sanie_category_type,p_account uuid,p_category uuid,p_subcategory uuid,p_amount numeric,p_date date,p_description text,p_payment_method text,p_request uuid,p_generation bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare u uuid; existing public.transactions%rowtype; available numeric; result public.transactions%rowtype;
begin u:=public.sanie_require_generation(p_generation);
 if p_amount is null or p_amount<=0 or scale(p_amount)>2 then raise exception using errcode='P0001',message='VALIDATION_ERROR'; end if;
 select * into existing from public.transactions where user_id=u and client_request_id=p_request limit 1;
 if found then if existing.transaction_type=p_type::text::public.sanie_transaction_type and existing.amount=p_amount and existing.account_id=p_account then return jsonb_build_object('transaction',to_jsonb(existing),'replayed',true); else raise exception using errcode='P0001',message='IDEMPOTENCY_MISMATCH'; end if; end if;
 perform public.sanie_assert_owned('public.accounts',p_account,u,false); perform public.sanie_assert_owned('public.categories',p_category,u,true);
 if p_subcategory is not null then perform public.sanie_assert_owned('public.subcategories',p_subcategory,u,true); end if;
 select balance into available from public.accounts where id=p_account and user_id=u and is_active and deleted_at is null for update;
 if not found then raise exception using errcode='P0001',message='FORBIDDEN_REFERENCE'; end if;
 if p_type='expense' and available<p_amount then raise exception using errcode='P0001',message='INSUFFICIENT_FUNDS'; end if;
 if not exists(select 1 from public.categories where id=p_category and category_type=p_type and deleted_at is null) then raise exception using errcode='P0001',message='VALIDATION_ERROR'; end if;
 insert into public.transactions(id,user_id,account_id,from_account_id,to_account_id,category_id,subcategory_id,amount,transaction_type,payment_method,client_request_id,transaction_date,description) values(p_id,u,p_account,case when p_type='expense' then p_account end,case when p_type='income' then p_account end,p_category,p_subcategory,p_amount,p_type::text::public.sanie_transaction_type,p_payment_method,p_request,p_date,p_description) returning * into result;
 perform public.sanie_rebuild_account(p_account,u);
 return jsonb_build_object('transaction',to_jsonb(result),'account_balance',(select balance from public.accounts where id=p_account));
end $$;
create or replace function public.create_income(p_id uuid,p_account uuid,p_category uuid,p_subcategory uuid,p_amount numeric,p_date date,p_description text,p_payment_method text,p_client_request_id uuid,p_generation bigint) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select public.sanie_create_ordinary(p_id,'income',p_account,p_category,p_subcategory,p_amount,p_date,p_description,p_payment_method,p_client_request_id,p_generation) $$;
create or replace function public.create_expense(p_id uuid,p_account uuid,p_category uuid,p_subcategory uuid,p_amount numeric,p_date date,p_description text,p_payment_method text,p_client_request_id uuid,p_generation bigint) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select public.sanie_create_ordinary(p_id,'expense',p_account,p_category,p_subcategory,p_amount,p_date,p_description,p_payment_method,p_client_request_id,p_generation) $$;

create or replace function public.create_transfer(p_id uuid,p_from uuid,p_to uuid,p_amount numeric,p_fee numeric,p_fee_category uuid,p_date date,p_description text,p_request uuid,p_generation bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare u uuid; a numeric; x public.transactions%rowtype;
begin u:=public.sanie_require_generation(p_generation); if p_from=p_to or p_amount<=0 or coalesce(p_fee,0)<0 then raise exception using errcode='P0001',message='VALIDATION_ERROR'; end if;
 select * into x from public.transactions where user_id=u and client_request_id=p_request; if found then return jsonb_build_object('transfer',to_jsonb(x),'replayed',true); end if;
 perform public.sanie_assert_owned('public.accounts',p_from,u,false); perform public.sanie_assert_owned('public.accounts',p_to,u,false);
 perform 1 from public.accounts where id in(p_from,p_to) and user_id=u and is_active and deleted_at is null order by id for update;
 select balance into a from public.accounts where id=p_from; if a<p_amount+coalesce(p_fee,0) then raise exception using errcode='P0001',message='INSUFFICIENT_FUNDS'; end if;
 if coalesce(p_fee,0)>0 then perform public.sanie_assert_owned('public.categories',p_fee_category,u,true); end if;
 insert into public.transactions(id,user_id,account_id,from_account_id,to_account_id,amount,transaction_type,payment_method,client_request_id,transaction_date,description) values(p_id,u,p_from,p_from,p_to,p_amount,'transfer','transfer',p_request,p_date,p_description) returning * into x;
 if coalesce(p_fee,0)>0 then insert into public.transactions(id,user_id,account_id,from_account_id,category_id,amount,transaction_type,payment_method,transfer_parent_id,transaction_date,description) values(gen_random_uuid(),u,p_from,p_from,p_fee_category,p_fee,'expense','transfer',p_id,p_date,coalesce(p_description,'Transfer')||' Fee'); end if;
 perform public.sanie_rebuild_account(p_from,u); perform public.sanie_rebuild_account(p_to,u); return jsonb_build_object('transfer',to_jsonb(x)); end $$;

create or replace function public.create_goal_contribution(p_id uuid,p_goal uuid,p_account uuid,p_amount numeric,p_date date,p_description text,p_request uuid,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare u uuid; a numeric; t public.transactions%rowtype;
begin u:=public.sanie_require_generation(p_generation); perform public.sanie_assert_owned('public.goals',p_goal,u,false); perform public.sanie_assert_owned('public.accounts',p_account,u,false); select balance into a from public.accounts where id=p_account and user_id=u and is_active and deleted_at is null for update; if a<p_amount then raise exception using errcode='P0001',message='INSUFFICIENT_FUNDS'; end if;
 select * into t from public.transactions where user_id=u and client_request_id=p_request; if found then return jsonb_build_object('transaction',to_jsonb(t),'replayed',true); end if;
 insert into public.transactions(id,user_id,account_id,from_account_id,goal_id,amount,transaction_type,payment_method,client_request_id,transaction_date,description) values(p_id,u,p_account,p_account,p_goal,p_amount,'goal_contribution','goal',p_request,p_date,p_description) returning * into t; perform public.sanie_rebuild_goal(p_goal,u); perform public.sanie_rebuild_account(p_account,u); return jsonb_build_object('transaction',to_jsonb(t),'goal',(select to_jsonb(g) from public.goals g where id=p_goal)); end $$;

create or replace function public.update_account_opening_balance(p_account uuid,p_opening numeric,p_base_version bigint,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid; a public.accounts%rowtype; begin u:=public.sanie_require_generation(p_generation); select * into a from public.accounts where id=p_account and user_id=u and deleted_at is null for update; if not found then raise exception using errcode='P0001',message='NOT_FOUND'; end if; if a.version<>p_base_version then raise exception using errcode='P0001',message='CONFLICT'; end if; if scale(p_opening)>2 then raise exception using errcode='P0001',message='VALIDATION_ERROR'; end if; update public.accounts set opening_balance=p_opening where id=p_account; perform public.sanie_rebuild_account(p_account,u); return (select to_jsonb(x) from public.accounts x where id=p_account); end $$;

create or replace function public.update_transaction(p_id uuid,p_base_version bigint,p_amount numeric,p_date date,p_description text,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid; t public.transactions%rowtype; begin u:=public.sanie_require_generation(p_generation); select * into t from public.transactions where id=p_id and user_id=u and deleted_at is null for update; if not found then raise exception using errcode='P0001',message='NOT_FOUND'; end if; if t.version<>p_base_version then raise exception using errcode='P0001',message='CONFLICT'; end if; if t.transaction_type in ('transfer','goal_contribution') or t.karobar_transaction_id is not null or t.recurring_definition_id is not null then raise exception using errcode='P0001',message='INVALID_STATE'; end if; if p_amount<=0 or scale(p_amount)>2 then raise exception using errcode='P0001',message='VALIDATION_ERROR'; end if; update public.transactions set amount=p_amount,transaction_date=p_date,description=p_description where id=p_id; if t.account_id is not null then perform public.sanie_rebuild_account(t.account_id,u); end if; return (select to_jsonb(x) from public.transactions x where id=p_id); end $$;
create or replace function public.delete_transaction(p_id uuid,p_base_version bigint,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid; t public.transactions%rowtype; begin u:=public.sanie_require_generation(p_generation); select * into t from public.transactions where id=p_id and user_id=u and deleted_at is null for update; if not found then raise exception using errcode='P0001',message='NOT_FOUND'; end if; if t.version<>p_base_version then raise exception using errcode='P0001',message='CONFLICT'; end if; if t.transaction_type='transfer' or t.karobar_transaction_id is not null or t.recurring_definition_id is not null then raise exception using errcode='P0001',message='INVALID_STATE'; end if; update public.transactions set deleted_at=now() where id=p_id; if t.goal_id is not null then perform public.sanie_rebuild_goal(t.goal_id,u); end if; if t.account_id is not null then perform public.sanie_rebuild_account(t.account_id,u); end if; return jsonb_build_object('id',p_id,'deleted',true); end $$;
create or replace function public.update_goal_contribution(p_id uuid,p_base_version bigint,p_amount numeric,p_date date,p_description text,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid; t public.transactions%rowtype; a numeric; begin u:=public.sanie_require_generation(p_generation); select * into t from public.transactions where id=p_id and user_id=u and transaction_type='goal_contribution' and deleted_at is null for update; if not found then raise exception using errcode='P0001',message='NOT_FOUND'; end if; if t.version<>p_base_version then raise exception using errcode='P0001',message='CONFLICT'; end if; select balance+t.amount into a from public.accounts where id=t.account_id for update; if a<p_amount then raise exception using errcode='P0001',message='INSUFFICIENT_FUNDS'; end if; update public.transactions set amount=p_amount,transaction_date=p_date,description=p_description where id=p_id; perform public.sanie_rebuild_goal(t.goal_id,u); perform public.sanie_rebuild_account(t.account_id,u); return (select to_jsonb(x) from public.transactions x where id=p_id); end $$;
create or replace function public.delete_goal_contribution(p_id uuid,p_base_version bigint,p_generation bigint) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select public.delete_transaction(p_id,p_base_version,p_generation) $$;

create or replace function public.create_karobar_transaction(p_id uuid,p_person uuid,p_type public.sanie_karobar_type,p_amount numeric,p_account uuid,p_date date,p_due_date date,p_description text,p_request uuid,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid; k public.karobar_transactions%rowtype; begin u:=public.sanie_require_generation(p_generation); if p_amount<=0 or scale(p_amount)>2 then raise exception using errcode='P0001',message='VALIDATION_ERROR'; end if; select * into k from public.karobar_transactions where user_id=u and client_request_id=p_request; if found then return jsonb_build_object('karobar',to_jsonb(k),'replayed',true); end if; perform public.sanie_assert_owned('public.people',p_person,u,false); if p_account is not null then perform public.sanie_assert_owned('public.accounts',p_account,u,false); end if; if p_type<>'adjustment' and p_account is null then raise exception using errcode='P0001',message='VALIDATION_ERROR'; end if; insert into public.karobar_transactions(id,user_id,person_id,transaction_type,amount,account_id,client_request_id,transaction_date,due_date,description) values(p_id,u,p_person,p_type,p_amount,p_account,p_request,p_date,p_due_date,p_description) returning * into k;
 -- `sanie_rebuild_account` applies the established cash effects: lent/repaid
 -- reduce the account; borrowed/returned increase it. Adjustments are
 -- position-only until a reviewed adjustment direction is added.
 if p_account is not null then perform public.sanie_rebuild_account(p_account,u); end if; return jsonb_build_object('karobar',to_jsonb(k)); end $$;
create or replace function public.update_karobar_transaction(p_id uuid,p_base_version bigint,p_amount numeric,p_date date,p_description text,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid;k public.karobar_transactions%rowtype; begin u:=public.sanie_require_generation(p_generation);select * into k from public.karobar_transactions where id=p_id and user_id=u and deleted_at is null for update;if not found then raise exception using errcode='P0001',message='NOT_FOUND';end if;if k.version<>p_base_version then raise exception using errcode='P0001',message='CONFLICT';end if;if p_amount<=0 or scale(p_amount)>2 then raise exception using errcode='P0001',message='VALIDATION_ERROR';end if;update public.karobar_transactions set amount=p_amount,transaction_date=p_date,description=p_description where id=p_id;if k.account_id is not null then perform public.sanie_rebuild_account(k.account_id,u);end if;return(select to_jsonb(x)from public.karobar_transactions x where id=p_id);end $$;
create or replace function public.delete_karobar_transaction(p_id uuid,p_base_version bigint,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid;k public.karobar_transactions%rowtype;begin u:=public.sanie_require_generation(p_generation);select * into k from public.karobar_transactions where id=p_id and user_id=u and deleted_at is null for update;if not found then raise exception using errcode='P0001',message='NOT_FOUND';end if;if k.version<>p_base_version then raise exception using errcode='P0001',message='CONFLICT';end if;if k.expense_transaction_id is not null or k.income_transaction_id is not null then raise exception using errcode='P0001',message='INVALID_STATE';end if;update public.karobar_transactions set deleted_at=now()where id=p_id;if k.account_id is not null then perform public.sanie_rebuild_account(k.account_id,u);end if;return jsonb_build_object('id',p_id,'deleted',true);end $$;
create or replace function public.sanie_next_occurrence(r public.recurring_transactions) returns date language plpgsql immutable set search_path=pg_catalog as $$ begin return case r.frequency when 'daily' then r.next_occurrence+1 when 'weekly' then r.next_occurrence+7 when 'bi_weekly' then r.next_occurrence+14 when 'monthly' then (r.next_occurrence+interval '1 month')::date when 'quarterly' then (r.next_occurrence+interval '3 months')::date when 'yearly' then (r.next_occurrence+interval '1 year')::date end;end $$;
create or replace function public.process_recurring_occurrence(p_definition uuid,p_date date,p_action text,p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid; r public.recurring_transactions%rowtype; nid uuid; next_date date; begin u:=public.sanie_require_generation(p_generation);select * into r from public.recurring_transactions where id=p_definition and user_id=u and deleted_at is null and is_active for update;if not found then raise exception using errcode='P0001',message='NOT_FOUND';end if;if p_action not in('generate','skip') or r.next_occurrence<>p_date or p_date>current_date then raise exception using errcode='P0001',message='INVALID_STATE';end if;next_date:=public.sanie_next_occurrence(r);if p_action='skip' then update public.recurring_transactions set next_occurrence=case when end_date is not null and next_date>end_date then null else next_date end where id=p_definition;return jsonb_build_object('status','skipped','next_occurrence',next_date);end if;if exists(select 1 from public.transactions where user_id=u and recurring_definition_id=p_definition and recurring_occurrence_date=p_date and deleted_at is null) then update public.recurring_transactions set next_occurrence=next_date where id=p_definition;return jsonb_build_object('status','already_processed');end if;nid:=gen_random_uuid();perform public.sanie_create_ordinary(nid,r.transaction_type,r.account_id,r.category_id,r.subcategory_id,r.amount,p_date,r.description,'recurring',nid,p_generation);update public.transactions set recurring_definition_id=p_definition,recurring_occurrence_date=p_date where id=nid;update public.recurring_transactions set next_occurrence=case when end_date is not null and next_date>end_date then null else next_date end where id=p_definition;return jsonb_build_object('status','generated','transaction_id',nid,'next_occurrence',next_date);end $$;

create table public.fresh_start_operations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), prior_generation bigint not null, new_generation bigint not null, status text not null default 'completed', created_at timestamptz not null default now());
create or replace function public.fresh_start(p_generation bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare u uuid; new_g bigint; begin u:=public.sanie_require_generation(p_generation); update public.profiles set data_generation=data_generation+1 where id=u returning data_generation into new_g; insert into public.fresh_start_operations(user_id,prior_generation,new_generation) values(u,p_generation,new_g); -- Foundation intentionally does not destroy data: Phase 1C must approve reset scope before activation.
 return jsonb_build_object('data_generation',new_g,'status','boundary_created'); end $$;

revoke all on function public.sanie_require_generation(bigint),public.sanie_rebuild_account(uuid,uuid),public.sanie_rebuild_goal(uuid,uuid),public.sanie_create_ordinary(uuid,public.sanie_category_type,uuid,uuid,uuid,numeric,date,text,text,uuid,bigint) from public;
grant execute on function public.create_income(uuid,uuid,uuid,uuid,numeric,date,text,text,uuid,bigint),public.create_expense(uuid,uuid,uuid,uuid,numeric,date,text,text,uuid,bigint),public.create_transfer(uuid,uuid,uuid,numeric,numeric,uuid,date,text,uuid,bigint),public.create_goal_contribution(uuid,uuid,uuid,numeric,date,text,uuid,bigint),public.update_goal_contribution(uuid,bigint,numeric,date,text,bigint),public.delete_goal_contribution(uuid,bigint,bigint),public.update_transaction(uuid,bigint,numeric,date,text,bigint),public.delete_transaction(uuid,bigint,bigint),public.update_account_opening_balance(uuid,numeric,bigint,bigint),public.create_karobar_transaction(uuid,uuid,public.sanie_karobar_type,numeric,uuid,date,date,text,uuid,bigint),public.update_karobar_transaction(uuid,bigint,numeric,date,text,bigint),public.delete_karobar_transaction(uuid,bigint,bigint),public.process_recurring_occurrence(uuid,date,text,bigint),public.fresh_start(bigint) to authenticated;
